language: cpp
sudo: true
install:
  - sudo add-apt-repository -y ppa:hrg/daily
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-pip python-dev openrtm-aist openrtm-aist-python python-omniorb omniidl-python omniorb-nameserver omniorb-idl omniidl
  - sudo pip install pyyaml docutils rtsprofile rtctree nose rednose coverage coveralls
script:
  - sudo /etc/init.d/omniorb4-nameserver stop
  - nosetests -v --rednose --with-doctest --with-coverage --cover-package=rtshell --cover-erase test/*.py
  - coverage combine
  - coverage report
after_success:
  coveralls
